### ISSUE TITLE
Including a newline in the prompt - pressing backspace causes the prompt to print again.

### ISSUE THREAD

**Issue by zachdaniel** [octplane/rust-linenoise#5]
```rust
let val = linenoise::input("Hello\r\nDave -> ");
```

If you set the prompt to something like this, pressing backspace causes a new line.

A) Is it supposed to work that way?

B) If it is, how would I go about getting around it?

**Comment by octplane** [comment]
Hello,

Thanks for your message!

Re your issue, my guess is that:

A) This is the way is has been implemented by the original library designer
B) maybe poke around https://github.com/antirez/linenoise/blob/80fd0569d166cd32886a640e58f3bf292807a3c0/linenoise.c#L465 to change its behavior when the prompt is multi-line.

In any case, the rust binding merely wraps the C impl and cannot do anything to change this behavior. Maybe ask upstream ?
