### ISSUE TITLE
check we're using the most appropriate fork of the native code

### ISSUE THREAD

**Issue by cmsd2** [octplane/rust-linenoise#9]
there are hundreds of forks of antirez/linenoise
some are recent and seem fully featured like this one that was recently on HN: https://github.com/arangodb/linenoise-ng
if we're going to continue vendoring the native code, it seems worth checking that we're tracking an upstream codebase that is receiving some love. in this case the arangodb fork might come with cross-platform support built-in.

**Comment by octplane** [comment]
Yep. Will investigate :)

**Comment by octplane** [comment]
https://github.com/arangodb/linenoise-ng/pull/2

**Comment by octplane** [comment]
Can you check https://github.com/octplane/rust-linenoise/tree/arango agains win32 ? (I can probably do that but my win32 machine is outdated and at home... )

**Comment by cmsd2** [comment]
i had to comment out the use of linenoise::history_line in the example to get it to run.
i used a windows server 2012 64bit instance in aws:

msvc: works fine
mingw64: had to add .flag("--std=c++0x") to build.rs due to the use of char32_t
gnu on linux: also had to add .flag(...)

the flag to add is compiler specific, but adding it doesn't seem to break msvc weirdly.

**Comment by octplane** [comment]
Juste pushed the fix with history_line....

**Comment by cmsd2** [comment]
it seems msvc's compiler frontend cl.exe just ignores unknown options so that's why that works.
history works.
clear works.
